openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  # TODO: CHANGE TO HTTPS FOR PROD
  - url: http://localhost:8000/api

components:
  schemas:
    BasicAtp45Input:
      type: object
      required:
        - "coordinates"
      properties:
        locations:
          type: array
          items:
            $ref: '#/components/schemas/GeoPoint'
          description: 'Array of release points'
    WindAtp45Input:
      allOf:
        - $ref: '#/components/schemas/BasicAtp45Input'
        - type: object
          required:
            - wind
          properties:
            wind:
              $ref: '#/components/schemas/WindVelocity'
    ForecastAtp45Input:
      allOf:
        - $ref: '#/components/schemas/BasicAtp45Input'
        - type: object
          required:
            - date
          properties:
            datetime:
              type: string
              format: date-time
              description: 'Datetime of the forecast'
    
    WindVelocity:
      type: object
      required:
        - "speed"
        - "azimuth"
      properties:
        speed:
          type: number
          description: 'Wind speed - units [m/s]'
        azimuth:
          type: number
          description: 'angle from North - units [m/s]'
    GeoPoint:
      type: object
      required:
        - "lon"
        - "lat"
      properties:
        lon:
          type: number
          description: 'Longitude [°]'
        lat:
          type: number
          description: 'Latitude [°]'
    # TODO MBEOT: MODIFY ACCORDING TO ATP45.JL RESULT
    Atp45Result:
      type: object
      properties:
        coordinates:
          type: array
          items: 
            $ref: '#/components/schemas/GeoPoint'

  securitySchemes:
    name:
      type: http
      scheme: bearer
      bearerFormat: JWTpaths

  
paths:
  /atp45/run/forecast:
    post:
      description: 'Run ATP45 with forecast wind data'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForecastAtp45Input'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Atp45Result'

  /atp45/run/wind:
    post:
      description: 'Run ATP45 with request wind data'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WindAtp45Input'
      responses:
        '200':
          description: OK

